# Generated by Django 3.2 on 2025-11-10 09:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_highlight', models.CharField(default='About', help_text="The first part of the title (e.g. 'About')", max_length=100)),
                ('highlight_desc', models.CharField(default='The Group', help_text="The highlighted part of the title (e.g. 'The Group')", max_length=200)),
                ('image', models.ImageField(help_text='Main image for the About section', upload_to='about/')),
                ('sub_title', models.TextField(help_text='First paragraph text')),
                ('description', models.TextField(blank=True, help_text='Second paragraph text (optional)', null=True)),
                ('button_link', models.URLField(default='', help_text='Link for the Learn More button', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this About section')),
            ],
        ),
        migrations.CreateModel(
            name='Aen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description/AEN')),
                ('image', models.ImageField(upload_to='aen/')),
                ('link', models.URLField(blank=True, default='#', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title (e.g. Marketing Officer, Software Engineer)', max_length=200)),
                ('description', models.TextField(help_text='Short description or job details.')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('location', models.CharField(help_text='Job location, e.g. Dhaka, Chattogram', max_length=150)),
                ('post_date', models.DateField(help_text='The date this job was posted.')),
                ('deadline', models.DateField(help_text='Application deadline for this position.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', help_text='Set whether the job is currently active or closed.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the website.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this job from the website.')),
            ],
            options={
                'verbose_name': 'Career Opportunity',
                'verbose_name_plural': 'Career Opportunities',
                'ordering': ['order', '-post_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_highlight', models.CharField(default='ContactMessage', max_length=100)),
                ('highlight_desc', models.CharField(default='Contact Description', max_length=200)),
                ('address', models.CharField(default='Contact Address', max_length=200)),
                ('phone1', models.TextField(help_text='Contact phone1')),
                ('phone2', models.TextField(help_text='Contact phone2')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Csr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_highlight', models.CharField(default='Csr', help_text="The first part of the title (e.g. 'Csr", max_length=100)),
                ('highlight_desc', models.CharField(default='Group Csr', help_text="The highlighted part of the title (e.g. 'Group Csr')", max_length=200)),
                ('image', models.ImageField(help_text='Main image for the csr section', upload_to='csr/')),
                ('sub_title', models.TextField(help_text='First paragraph text')),
                ('description', models.TextField(blank=True, help_text='Second paragraph text (optional)', null=True)),
                ('button_link', models.URLField(default='', help_text='Link for the Learn More button', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this About section')),
            ],
        ),
        migrations.CreateModel(
            name='CsrHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Corporate Social Responsibility', max_length=255)),
                ('subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Subtitle')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='csr/')),
                ('button_text', models.CharField(default='Get Started', max_length=100)),
                ('button_link', models.URLField(default='#', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupBrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='brand_logos/')),
                ('link', models.URLField(blank=True, default='#', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Subtitle')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About/')),
                ('button_text', models.CharField(default='Learn More', max_length=100)),
                ('button_link', models.URLField(default='#', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title of the slide', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=255, null=True)),
                ('background_image', models.ImageField(help_text='Background image for the banner', upload_to='Carousel/')),
                ('primary_button_text', models.CharField(default='Our Services', max_length=100)),
                ('primary_button_link', models.URLField(default='#', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this slide')),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Join Us', max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='See More', max_length=100)),
                ('button_link', models.URLField(default='#', max_length=300)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='join_us/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_highlight', models.CharField(default='KeyManagement', max_length=100)),
                ('highlight_desc', models.CharField(default='Group KeyManagement', max_length=200)),
                ('image', models.ImageField(upload_to='key_management/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the page.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this person from the website.')),
            ],
        ),
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload partner logo or image', upload_to='partners/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='#', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
