# Generated by Django 3.2 on 2025-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='highlight_desc',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='title_highlight',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='button_text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='heading1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='heading2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='list_items1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='list_items2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_images/'),
        ),
    ]
