# Generated by Django 3.2 on 2025-11-10 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0002_auto_20251110_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='description1',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
