# Generated by Django 3.2 on 2025-11-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0005_auto_20251110_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_highlight', models.CharField(default='KeyManagement', max_length=100)),
                ('highlight_desc', models.CharField(default='Group KeyManagement', max_length=200)),
                ('image', models.ImageField(upload_to='key_management/')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the page.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this person from the website.')),
            ],
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
