# Generated by Django 3.2 on 2025-11-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0006_auto_20251110_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csr',
            old_name='sub_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='csr',
            name='highlight_desc',
        ),
        migrations.RemoveField(
            model_name='csr',
            name='title_highlight',
        ),
    ]
