# Generated by Django 3.2 on 2025-11-16 11:27

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0007_auto_20251110_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_1', models.CharField(max_length=255)),
                ('link_2', models.CharField(max_length=255)),
                ('link_3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='highlight_desc',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='title_highlight',
        ),
        migrations.RemoveField(
            model_name='keymanagement',
            name='highlight_desc',
        ),
        migrations.RemoveField(
            model_name='keymanagement',
            name='title_highlight',
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description/AEN'),
        ),
        migrations.AlterField(
            model_name='aen',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description/AEN'),
        ),
        migrations.AlterField(
            model_name='careeropportunity',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Short description or job details.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='csr',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Second paragraph text (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='csrhome',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='csrhome',
            name='subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homeaboutsection',
            name='subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='keymanagement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keymanagement',
            name='designation',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='ourpartner',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
